version: '2'

services:
    zookeeper:
        image: wurstmeister/zookeeper
        ports:
            - "2181:2181"
    kafka:
        image: wurstmeister/kafka
        ports:
            - "9092:9092"
        environment:
            KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
            KAFKA_ADVERTISED_PORT: 9092
            KAFKA_CREATE_TOPICS: "test:1:1,updates:1:1"
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    redis:
        image: redis
        ports:
          - "6379:6379"
    influx:
        image: influxdb
        ports:
          - "8086:8086"
        volumes:
          - influxdb-storage:/var/lib/influxdb
        environment:
          - INFLUXDB_DB=flink
    grafana:
        image: grafana/grafana
        ports:
         - "3000:3000"
        volumes:
         - grafana-storage:/var/lib/grafana

    flinkjm:
        image: flink
        expose:
          - "6123"
        ports:
          - "8081:8081"
        command: jobmanager
        environment:
          - JOB_MANAGER_RPC_ADDRESS=jobmanager
        volumes:
          - ./docker-flink/conf:/opt/flink/conf
    flinktm:
        image: flink
        expose:
          - "6121"
          - "6122"
        depends_on:
          - flinkjm
        links:
          - "flinkjm:jobmanager"
        command: taskmanager
        environment:
          - JOB_MANAGER_RPC_ADDRESS=jobmanager
        volumes:
          - ./docker-flink/conf:/opt/flink/conf

volumes:
    grafana-storage:
    influxdb-storage:

